### ISSUE TITLE
window shading is off

### ISSUE THREAD

**Issue by tomammon** [bartobri/bmenu#7]
Hi, 

Thanks for the great tool, it was exactly what I was looking for. It functions well, but it doesn't look very good, see the attached screenshot. I'm using centos 7 with ncurses-devel-5.9-13.20130511.el7.x86_64

![image](https://cloud.githubusercontent.com/assets/24750322/21707811/c6dbe4d2-d38f-11e6-9953-38459072fc30.png)

**Comment by bartobri** [comment]
Hi. Glad you found it useful!

Yeah, this looks weird. There isn't any code in my project that specifically prints those border characters you are seeing. My assumption is that it is something inside the ncurses library that is degrading the extended character set into plain ascii, possibly due to your terminal settings. Based on the logo in your screen shot, are you using putty?

If so, try playing with your putty settings. Make sure support for UTF-8 is enabled. Also make sure ANSI/VT100 support is enabled.

- Brian

**Comment by tomammon** [comment]
I am indeed using putty. My settings match what you have specified, here are some screenshots of those. 

![image](https://cloud.githubusercontent.com/assets/24750322/21747012/25fe206a-d516-11e6-8c07-fd98765a334e.png)

![image](https://cloud.githubusercontent.com/assets/24750322/21747013/36d3ffb8-d516-11e6-8963-13f1854fac2f.png)

**Comment by tomammon** [comment]
I just tried it on a mac and all of the colors and shading look fine. So maybe it's something with my version of ncurses and putty.

**Comment by bartobri** [comment]
I would assume it is more likely an issue with your putty configuration. I don't have a windows system and don't use putty so I can't help you. I suggest trying playing with the configs under "Adjust how PuTTY handles line drawing characters".

**Comment by bartobri** [comment]
Closing this since it appears to be an issue with the terminal program.
